[phases.setup]
nixPkgs = ["php84", "php84Extensions.intl", "php84Extensions.zip", "php84Extensions.opcache", "php84Extensions.pdo", "php84Extensions.pdo_mysql", "php84Extensions.mbstring", "php84Extensions.tokenizer", "php84Extensions.xml", "php84Extensions.ctype", "php84Extensions.curl", "php84Extensions.fileinfo"]

[phases.build]
cmds = ["npm install", "npm run build", "composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php artisan optimize && php artisan serve --host=0.0.0.0 --port=$PORT"